// src/components/Footer.jsx
export default function Footer() {
	return (
		<footer className="site-footer">
			<div className="container footer-row">
				<small>© {new Date().getFullYear()} Tucha Guerra. Todos os direitos reservados.</small>
				<small>
					<a href="#top">Voltar ao topo ↑</a>
				</small>
			</div>
		</footer>
	)
}

// src/components/Footer.vue
<template>
	<footer class="border-t border-border !text-white pb-[calc(14px+env(safe-area-inset-bottom))]">
			<div class="container">
				<div class="flex flex-col gap-2 py-6 text-base sm:flex-row sm:items-center sm:justify-between">
					<span class="!text-white">© {{ new Date().getFullYear() }} Eduardo Cebola. Todos os direitos reservados.</span>
					<span><a href="#top" class="!text-white transition-opacity duration-150 hover:opacity-80">Topo ↑</a></span>
				</div>
			</div>
	</footer>
</template>
