// src/components/Header.vue
<template>
  <header class="site-header">
    <div class="container header-row">
      <a href="#top" class="brand">EQMC</a>
      <nav class="nav">
        <a href="#about" class="btn">Sobre</a>
        <a href="#contact" class="btn primary">Contacto</a>
      </nav>
    </div>
  </header>
</template>

// src/components/Header.jsx
export default function Header() {
	return (
		<header className="site-header">
			<div className="container header-row">
				<a href="#top" className="brand">Estórias que me Contaram</a>
				<nav className="nav">
					<a href="#about" className="btn">Sobre</a>
					<a href="#contact" className="btn">Contacto</a>
				</nav>
			</div>
		</header>
	)
}
