// src/sections/Contact.jsx
export default function Contact() {
	return (
		<section id="contact" className="section">
			<div className="container">
				<h2>Contacto</h2>
				<p>
					Para comprar o livro ou se tiver alguma dúvida, 
					use o formulário abaixo.
				</p>
				<form className="form">
					<label>
						<span>Nome</span>
						<input type="text" name="name" required />
					</label>
					<label>
						<span>Email</span>
						<input type="email" name="email" required />
					</label>
					<label>
						<span>Mensagem</span>
						<textarea name="message" rows="5" required />
					</label>

					<button type="submit" className="btn primary">Enviar</button>
				</form>
			</div>
		</section>
	)
}

// src/sections/Contact.vue
<template>
  <section id="contact" class="section">
    <div class="container">
      <h2>Contacto</h2>
      <p>Para comprar o livro ou tirar dúvidas, use o formulário.</p>

      <form action="https://formspree.io/f/your-id" method="POST" class="form">
        <label>
          <span>Nome</span>
          <input type="text" name="name" required />
        </label>
        <label>
          <span>Email</span>
          <input type="email" name="email" required />
        </label>
        <label>
          <span>Mensagem</span>
          <textarea name="message" rows="5" required />
        </label>
        <button type="submit" class="btn primary">Enviar</button>
      </form>
    </div>
  </section>
</template>
