// src/App.jsx
import { useEffect } from 'react'
import Header from './components/Header'
import About from './sections/About'
import Contact from './sections/Contact'
import Footer from './components/Footer'

export default function App() {
	useEffect(() => {
		if ("scrollRestoration" in window.history) {
			window.history.scrollRestoration = "manual";
		}
		window.scrollTo(0, 0);
	}, [])
  return (
		<div id="top">
			<Header />
			<main>
				<About />
				<Contact />
			</main>
			<Footer />
		</div>
  )
}

// src/App.vue
<script setup>
	import { onMounted } from 'vue'
	import IntroOverlay from './components/IntroOverlay.vue'
	import Header from './components/Header.vue'
	import About from './sections/About.vue'
	import Contact from './sections/Contact.vue'
	import Footer from './components/Footer.vue'

	if ("scrollRestoration" in history) history.scrollRestoration = "manual"
	onMounted(() => window.scrollTo(0, 0))
</script>

<template>
  <div id="top">
		<IntroOverlay />
    <Header />
    <main>
      <About />
      <Contact />
    </main>
    <Footer />
  </div>
</template>
